### ISSUE TITLE
Initial release (0.1.0)

### ISSUE THREAD

**Issue by Findeton** [sequentech/new-ballot-verifier#5]
* [x] sequentech/new-ballot-verifier#1
* [x] sequentech/new-ballot-verifier#2
* [x] sequentech/new-ballot-verifier#4 
* [x] sequentech/new-ballot-verifier#6 
* [x] sequentech/new-ballot-verifier#7 
* [x] sequentech/new-ballot-verifier#10 
* [x] sequentech/new-ballot-verifier#3  
* [x] sequentech/new-ballot-verifier#9 
* [x] sequentech/roadmap#2
* [x] sequentech/roadmap#45

## Dependencies PRs

* https://github.com/sequentech/sequent-core/pull/14
* https://github.com/sequentech/new-ballot-verifier/pull/28
